config/routes.php
<?php
use Cake\Routing\Router;
use App\Routing\Route;
use Cake\Core\Configure;
use Cake\Core\App;

Router::plugin('UserManager',["path"=>"/user-manager"], function ($routes) {

    $routes->connect("/",[
        "controller"=>"Accounts",
        "action"=>"index"
    ]);

    $routes->connect("/:controller",["action"=>"index"]);

    $routes->connect("/:controller/:action");

    $routes->fallbacks("DashedRoute");

});


Router::prefix("admin",function($routes) {


    $routes->plugin("UserManager",["path"=>"/user-manager"],function($routes) {

        $routes->connect("/",[
            "controller"=>"Accounts",
            "action"=>"index"
        ]);

        $routes->connect("/:controller",["action"=>"index"]);

        $routes->connect("/:controller/:action");

        $routes->fallbacks("DashedRoute");

    });

});


$path = App::path("Auth/Provider","UserManager");

$providers = [];

foreach(scandir($path[0]) as $v)
{
	if(in_array($v,['.','..']) 
		|| !preg_match('/\.php$/',$v) 
		|| preg_match('/ProviderBase/',$v)
	) {
		continue;
	}

	$providers[] = preg_replace('/(.*)(\.php$)/','$1',$v);

}

foreach($providers as $v) {

	if(Configure::read("UserManager.{$v}LoginEnable")) {

		Router::connect(Configure::read("UserManager.{$v}AuthRedirectUrl"),[
			"plugin"=>"UserManager",
			"controller"=>"Login",
			"action"=>"handleForeignLogin"
		]);
	}

}


#Profile
Router::connect("/profile/:uri",
	[
		'plugin'=>'UserManager',
		'controller'=>'Profile',
		'action'=>'view'
	],
	[
		'uri'=>"[a-z\-\.]{2,}.html"
	]
);

src/Model/Table/UserCommentsTable.php
<?php
namespace UserManager\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * UserComments Model
 *
 * @property \UserManager\Model\Table\UserAccountsTable|\Cake\ORM\Association\BelongsTo $UserAccounts
 * @property |\Cake\ORM\Association\BelongsTo $ParentUserComments
 * @property |\Cake\ORM\Association\HasMany $ChildUserComments
 *
 * @method \UserManager\Model\Entity\UserComment get($primaryKey, $options = [])
 * @method \UserManager\Model\Entity\UserComment newEntity($data = null, array $options = [])
 * @method \UserManager\Model\Entity\UserComment[] newEntities(array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserComment|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \UserManager\Model\Entity\UserComment patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserComment[] patchEntities($entities, array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserComment findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 * @mixin \Cake\ORM\Behavior\TreeBehavior
 */
class UserCommentsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('user_comments');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');
        $this->addBehavior('Tree');

        $this->belongsTo('UserAccounts', [
            'foreignKey' => 'user_account_id',
            'className' => 'UserManager.UserAccounts'
        ]);
        $this->belongsTo('ParentUserComments', [
            'className' => 'UserManager.UserComments',
            'foreignKey' => 'parent_id'
        ]);
        $this->hasMany('ChildUserComments', [
            'className' => 'UserManager.UserComments',
            'foreignKey' => 'parent_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->allowEmpty('model');

        $validator
            ->allowEmpty('foreign_key');

        $validator
            ->allowEmpty('title');

        $validator
            ->allowEmpty('comment');

        $validator
            ->boolean('active')
            ->allowEmpty('active');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_account_id'], 'UserAccounts'));
        $rules->add($rules->existsIn(['parent_id'], 'ParentUserComments'));

        return $rules;
    }

	public function setTreeScope($model, $fk)
	{

		$this->behaviors()->Tree->config('scope',[
			'model'=>$model,
			'foreign_key'=>$fk
		]);

	}

	public function returnComments($model, $fk, $options = [])
	{

		$this->setTreeScope($model, $fk);

		$comments = $this->find('threaded',[
			'conditions'=>[
				'UserComments.model'=>$model,
				'UserComments.foreign_key'=>$fk
			],
			'order'=>[
				'UserComments.created'=>'DESC'
			],
			'contain'=>[
				'UserAccounts'
			]
		]);

		return $comments;

	}

	public function createComment(\UserManager\Model\Entity\UserComment $UserComment)
	{

		$this->setTreeScope($UserComment->model, $UserComment->foreign_key);

		return $this->save($UserComment);

	}




}

src/Controller/CommentsController.php
<?php

namespace UserManager\Controller;


use UserManager\Controller\AppController;


class CommentsController extends AppController
{

	public function initialize($conf = [])
	{

		parent::initialize($conf);

		$this->loadModel("UserManager.UserComments");

	}

	public function beforeFilter(\Cake\Event\Event $event)
	{
		parent::beforeFilter($event);
	}

	public function create()
	{

		if($this->request->is(['post','put'])) {

			$return_uri = $this->request->data("return_uri");

			$userComment = $this->UserComments->newEntity($this->request->data());

			$userComment->user_account_id = $this->Auth->user("id");

			if(($newComment = $this->UserComments->createComment($userComment)) !== False) {

                $url = parse_url($return_uri);

                $query = [];

                parse_str($url['query'], $query);

                $query['comment'] = $newComment->id;

                $qs = http_build_query($query);

                $goTo = "{$url['path']}?{$qs}";

				$this->Flash->success("Comment added successfully");

				$this->redirect($goTo);

			}

		}

	}

    public function form()
    {

        $model = $this->request->query("model");
        $foreign_key = $this->request->query("foreign_key");
        $return_uri = $this->request->query("return_uri");
        $options = [];
        if($this->request->query("parent_id")) {
            $options["parent_id"] = $this->request->query("parent_id");
        }
        $this->set(compact(
            "model",
            "foreign_key",
            "return_uri",
            "options"
        ));


    }


}

src/Template/Element/comments/comment-form.ctp
<?php

if(!isset($return_uri)) {
	$return_uri = $_SERVER['REQUEST_URI'];
}
?>
<?php
echo $this->Form->create(new \UserManager\Model\Entity\UserComment(),[
	'url'=>[
		'plugin'=>'UserManager',
		'controller'=>'Comments',
		'action'=>'create',
		'prefix'=>false
    ],
    'class'=>'comment-form'
	]);
?>
<?php
	echo $this->Form->input("return_uri",['type'=>'hidden','value'=>$return_uri]);
	echo $this->Form->input("model",['type'=>'hidden','value'=>$model]);
	echo $this->Form->input("foreign_key",['type'=>'hidden','value'=>$foreign_key]);
	if(isset($parent_id) && $parent_id) {
		echo $this->Form->input("parent_id",['type'=>'hidden','value'=>$parent_id]);
	}

?>

<?= $this->Form->input("comment",['type'=>'textarea']) ?>
<div class="submit clearfix">
	<div class="markdown-legend pull-left">
		Markdown Formatting	Accepted. ( <a href='https://en.wikipedia.org/wiki/Markdown#Example' target='_blank'>View Examples</a> )
	</div>

	<div class="btn-group pull-right">
		<button type="submit" class="btn btn-primary">Add Comment</button>
	</div>
</div>
<?php
	echo $this->Form->end();
?>
<script type="text/javascript">
	$("form.comment-form textarea.form-control").bind('keyup',function(e) {
		$(this).height(0).height(this.scrollHeight);
	})
</script>

src/Template/Element/comments/threaded-comment.ctp
<?php


if(!empty($comment->parent_id)) {
    $reply_id = $comment->parent_id;
} else {
    $reply_id = $comment->id;
}
?>
<a name="comment<?= $comment->id ?>"></a>
<div class="threaded-comment">
    <div class="comment">
        <div class="row">
            <div class="col-xs-2">
                <div class="user">
                    <div class="user-avatar">
                        <img src="https://gravatar.com/avatar/<?= md5(strtolower(trim($post->user_account->email))) ?>?s=150&d=mm&r=x" alt="" class='gravatar' />
                    </div>
                    <div class="user-name">
                        <?= "{$comment->user_account->first_name} {$comment->user_account->last_name}" ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-10">
                <div class="date-time">
                    <?= $comment->created->format("F dS, Y @ g:ia") ?>
                </div>
                <div class="comment-text">
                    <?= Parsedown::instance()
                        ->setBreaksEnabled(true)
                        ->text($comment->comment) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pull-right btn-group reply-btn-group">
                        <button class="btn btn-success btn-sm" data-comment-id='<?= $reply_id ?>'>
                            <i class="fa fa-reply" aria-hidden="true"></i>
                                Reply
                        </button>
                        <button class="btn btn-primary btn-sm" onclick='$(".comment-form:eq(0)").find("textarea").focus();'>
                            <i class="fa fa-edit"></i>
                            New Comment
                        </button>
                        <?php
                            $formAjaxUrl = $this->UserManager->commentFormAjaxUri($comment->model, $comment->foreign_key, $this->request->here, ['parent_id'=>$reply_id]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="reply-form" data-comment-id='<?= $comment->id ?>'></div>
        <div class="replies">
            <?php if(count($comment->children)>0):
                    $children = new \Cake\Collection\Collection($comment->children);
                    $children = $children->sortBy("created", SORT_ASC);
            ?>
                <?php foreach($children as $k=>$v): ?>
                    <?= $this->element('UserManager.comments/threaded-comment',['comment'=>$v, "parent_id"=>$comment->id]) ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php if(!isset($parent_id)): ?>
<script type="text/javascript">
    (function($) {
        var $reply = $("button[data-comment-id=<?= $comment->id ?>]");
        var $container = $("div[data-comment-id=<?= $comment->id ?>]");
        $reply.bind('click', function(e) {
            $(this).attr({"disabled": true});

            $.get('<?= $formAjaxUrl ?>', function(html) {
                var $form = $(html);
                $container.html($form);
                $(e.target).attr({"disabled": false});
                $form.find('textarea').focus();
            });
        });
    })(jQuery);
</script>
<?php endif; ?>